name: lite
channels:
  - conda-forge
dependencies:
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - bzip2=1.0.8=hd037594_8
  - c-ares=1.34.5=h5505292_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cairo=1.18.4=h6a3b0d2_0
  - click=8.3.0=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py312ha0dd364_2
  - cpython=3.12.12=py312hd8ed1ab_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - double-conversion=3.3.1=h286801f_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - faiss=1.9.0=py312h423fd24_0_cpu
  - faiss-cpu=1.9.0=hd610c6a_0
  - ffmpeg=8.0.0=gpl_h670d5b4_106
  - filelock=3.20.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312h5748b74_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - fsspec=2025.10.0=pyhd8ed1ab_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - giflib=5.2.2=h93a5062_0
  - glslang=16.0.0=h60b4770_0
  - gmp=6.3.0=h7bae524_2
  - gmpy2=2.2.1=py312h711ec26_1
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhd8ed1ab_0
  - harfbuzz=12.1.0=haf38c7b_0
  - hdbscan=0.8.39=py312ha11c99a_1
  - hdf5=1.14.6=nompi_he65715a_103
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - imath=3.2.2=h3470cca_0
  - jasper=4.2.8=hc0e5025_0
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.5.2=pyhd8ed1ab_0
  - kiwisolver=1.4.9=py312hdc12c9d_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.4=hcbd7ca7_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libclang-cpp19.1=19.1.7=default_h73dfc95_5
  - libclang13=21.1.4=default_h6e8f826_0
  - libcurl=8.16.0=hdece5d2_0
  - libcxx=21.1.4=hf598326_2
  - libde265=1.0.15=h2ffa867_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.1=hec049ff_0
  - libfaiss=1.9.0=h682f5e0_0_cpu
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.1=he69a767_1
  - libheif=1.19.7=gpl_h79e6334_100
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libhwy=1.3.0=h48b13b8_1
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h3dcb153_5
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - libllvm19=19.1.7=h8e0c9ce_2
  - libllvm21=21.1.4=h8e0c9ce_0
  - liblzma=5.8.1=h39f12f2_2
  - libnghttp2=1.67.0=hc438710_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_3
  - libopencv=4.12.0=qt6_py312h6fef4ab_607
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libpq=18.0=h31f7a3a_0
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.60.0=h5c55ec3_0
  - libsqlite=3.50.4=hf8de324_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.1=h7dc4979_0
  - libtorch=2.8.0=cpu_generic_h853542e_1
  - libusb=1.0.29=hbc156a2_0
  - libuv=1.51.0=h6caf38d_1
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - llvmlite=0.45.1=py312hc82e5dd_0
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.3=py312h5748b74_0
  - matplotlib=3.10.7=py312h1f38498_0
  - matplotlib-base=3.10.7=py312h605b88b_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mpc=1.3.1=h8f1351a_1
  - mpfr=4.2.1=hb693164_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - networkx=3.5=pyhe01879c_0
  - nomkl=1.0=h5ca1d4c_0
  - numba=0.62.1=py312hd24c766_0
  - numpy=1.26.4=py312h8442bc7_0
  - opencv=4.12.0=qt6_py312h5b798a3_607
  - openexr=3.4.2=h6aeeebb_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openjph=0.24.5=h23bdaea_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.5.4=h5503f6c_0
  - optree=0.17.0=py312ha0dd364_1
  - packaging=25.0=pyh29332c3_1
  - pango=1.56.4=h875632e_0
  - pcre2=10.46=h7125dd6_0
  - pillow=11.3.0=py312h2525f64_3
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pugixml=1.15=hd3d436d_0
  - py-opencv=4.12.0=qt6_py312he92a2c1_607
  - pybind11=2.13.6=pyhff21bea_3
  - pybind11-abi=4=hd8ed1ab_3
  - pybind11-global=2.13.6=pyh217bc35_3
  - pygments=2.19.2=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - python=3.12.12=h18782d2_1_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-multipart=0.0.20=pyhff2d567_0
  - python_abi=3.12=8_cp312
  - pytorch=2.8.0=cpu_generic_py312_h05d1414_1
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.9.3=hb266e41_0
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - rich=14.2.0=pyhcf101f3_0
  - scikit-learn=1.7.2=py312h79e0ffc_0
  - scipy=1.16.3=py312ha6bbf71_0
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.26=h919df07_0
  - setuptools=80.9.0=pyhff2d567_0
  - shaderc=2025.4=h1a5098f_0
  - six=1.17.0=pyhe01879c_1
  - sleef=3.9.0=hb028509_0
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - spirv-tools=2025.4=ha7d2532_0
  - starlette=0.49.1=pyhfdc7a7d_0
  - svt-av1=3.1.2=h12ba402_0
  - sympy=1.14.0=pyh2585a3b_105
  - tbb=2022.3.0=h66ce52b_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=h892fb3f_2
  - torchvision=0.24.0=cpu_py312_h4b3bcb2_1
  - torchvision-extra-decoders=0.0.2=py312h175c3de_4
  - tornado=6.5.2=py312h163523d_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - umap-learn=0.5.9.post2=py312h81bd7bf_0
  - unicodedata2=16.0.0=py312h163523d_1
  - uvicorn=0.38.0=pyh31011fe_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zstd=1.5.7=h6491c7d_2

prefix: "/Users/lwj/.local/share/mamba/envs/lite"
